<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<link rel="stylesheet" type="text/css" href="global/css/default.css" />
    <link rel="stylesheet" type="text/css" href="global/css/tooltip.css" />
    <link id="dcss" rel="stylesheet" type="text/css" href="#" />
	<script type="text/javascript" src="global/js/jquery/jquery.js"></script>

    <script type="text/javascript" src="global/js/yui/yahoo-dom-event/yahoo-dom-event.js"></script>
	<script type="text/javascript" src="global/js/yui/dragdrop/dragdrop-min.js"></script>
    <script type="text/javascript" src="global/js/common.js"></script>
	<script type="text/javascript" src="global/js/ux_palette_base.js"></script>
	<script type="text/javascript" src="global/js/jquery/plugins/jquery.dimensions.js"></script>
	<script type="text/javascript" src="global/js/jquery/plugins/jquery.tooltip.js"></script>
   	<script type="text/javascript" src="global/js/action_dialogs_common.js"></script>
	<script type="text/javascript" src="compare_baselines.php.js"></script>
	<title>Compare Baselines</title>
</head>
<body class="action_dialog wizard idd">
	<div id="wrapper_action_dialog_header" class="header rfq">
        <div class="header_wrapper">
            <div class="column_one">
                <h2 id="header_title">Compare Baselines</h2>
                <p>Program &bull; New Product development</p>
            </div>		
        </div>
        <div id="page_message" class="message info">
            <p id="step_message">Help text...</p>
        </div>
	</div>
	<div id="wrapper_action_dialog_content" class="content">
		<form id="form1" name="form1" action="#">
        	<!-- ****************************** -->
			<!-- 	STEP #1						-->
        	<!-- ****************************** -->
            <div id="step_1" class="step">
				<dl class="side_by_side_mixed with_top_margin">
               		<!-- Required Select -->
                    <dt class="required"><label for="req_sel_00">Compare Baseline:</label></dt>
                    <dd>
                        <select id="req_sel_00" class="medium_width">
                            <option>Current (name here)</option>
                            <option>TBD</option>
                   		 </select>
                    	<span class="error_msg hidden">Error message...</span>
                    </dd>
                    <dt class="required"><label for="req_sel_01">To Baseline:</label></dt>
                    <dd>
                        <select id="req_sel_01" class="medium_width">
                            <option>Next Recently Created Baseline (name here)</option>
                            <option>TBD</option>
                   		 </select>
                    	<span class="error_msg hidden">Error message...</span>
                    </dd>
                </dl>
            </div>
        	<!-- ****************************** -->
			<!-- 	STEP #2 					-->
        	<!-- ****************************** -->
            <div id="step_2" class="step">
                <div id="format_results_body_1" class="shuttle_control">
                    <fieldset class="dynamic">
                        <!-- COMPARE BASELINES - 3/27/08 Hector@naviscent -->
                        <!-- Note: No generic CSS generated. Inline CSS was used to place 
                        images since this object will be generated by Agiles' framework -->
                        <div>
                            <div class="column_zero">
                                <div style="border-right:1px solid silver; height: 235px;  width: 267px; background-color: #FFFFFF; float: left; min-height: 100px; overflow-x:hidden; overflow-y: auto;">
                                    <img src="../../../global/images/baseline_left.png"/>
                                </div>
                            </div>
                            <div class="column_one">
                                <div style="border:1px thin silver; height: 235px; width: 357px; background-color: #FFFFFF; float: left; margin-left: 10px; min-height: 100px; overflow-x:hidden; overflow-y: auto;">
                                    <img src="../../../global/images/baseline_right.png" border="0" usemap="#Map"/>
<map name="Map" id="Map"><area shape="rect" coords="272,20,355,231" href="#" /></map>
                                </div>
                          </div>
                        </div>
                    </fieldset> 
                    <div style="border:1px thin silver; width:188px; float:right; height:71px; position:relative; right:29px; top:6px;">
                           <img src="../../../global/images/baseline_legend.png"/>
                    </div>
                </div>
           	</div>
            <!-- ****************************** -->
			<!-- 	Info POP					-->
        	<!-- ****************************** -->
            <div id="ux_palette" class="ux_palette infopop">
        		<div id="ux_palette_top" class="ux_palette_top">
                    <div id="ux_palette_header" class="ux_palette_header">
                        <a id="ux_palette_toggle" class="ux_palette_toggle" href="#"></a>
                        <h4 id="ux_palette_title" class="ux_palette_title">NPD2: Modification - General Info Details</h4>
                        <a id="ux_palette_close" class="ux_palette_close" href="#"><span>close</span></a>
                    </div>

                    <div id="ux_palette_main" class="ux_palette_main">
                        <table class="baseline">
                            <thead>
                                <tr><th>&nbsp;</th><th>Baseline 1</th><th>Current</th></tr>
                            </thead>
                            <tbody>
                                <tr><th class="text">Schedule Start Date:</th><td>8/27/2008</td><td>7/08/2008</td></tr>
                                <tr><th class="text">Schedule Duration:</th><td>49</td><td>92</td></tr>
                                <tr><th class="text">Schedule End Date:</th><td>11/01/2008</td><td>11/12/2008</td></tr>
                                <tr><th class="text">Actual Start Date:</th><td></td><td>03/31/2008</td></tr>
                                <tr><th class="text">Actual Duration:</th><td></td><td>2</td></tr>
                                <tr><th class="text">Status:</th><td>Not Started</td><td>In Process</td></tr>
                                <tr><th class="text">Variance:</th><td>0</td><td>-161</td></tr>
                                <tr><th class="text">Status Type:</th><td>Pending</td><td>Review</td></tr>
                                <tr><th class="text">Days Effort:</th><td>31</td><td>215</td></tr>
								<tr><th class="text">Estimated Start Date:</th><td>8/27/2008</td><td>7/08/2008</td></tr>
                                <tr><th class="text">Estimated End Date:</th><td>11/01/2008</td><td>11/12/2008</td></tr>
                                <tr><th class="text">Estimated Duration:</th><td>49</td><td>92</td></tr>
                            </tbody>
                        </table>
                    </div>

                    <div id="ux_palette_bottom" class="ux_palette_bottom">
                        <div id="ux_palette_bottom_action_bar" class="ux_palette_bottom_action_bar">
                            <div class="right_column">
                                <a href="#" id="ux_palette_cmdBack" class="button"><span><em class="arrow_back">&nbsp;</em>Back</span></a> 
                                <a href="#" id="ux_palette_cmdNext" class="button"><span>Next<em class="arrow_next">&nbsp;</em></span></a>              
                                <a href="#" id="ux_palette_cmdCancel" class="button"><span><em class="cancel">&nbsp;</em>Cancel</span></a>
                            </div>
                            <div class="left_column">&nbsp;</div>
                        </div>
                        <div id="ux_palette_handle" class="ux_palette_handle">&nbsp;</div>
                    </div>
    			</div>
            </div>
		</form>
	</div>
    <div id="wrapper_action_dialog_footer" class="footer">
	    <div class="column_one">
	    </div>
    	<div class="column_three">
	        <a href="#" id="cmdBack" class="button"><span><em class="arrow_back">&nbsp;</em>Back</span></a> 
    	    <a href="#" id="cmdNext" class="button"><span class="active">Next<em class="arrow_next">&nbsp;</em></span></a>
    	    <a href="#" id="cmdCancel" class="button"><span><em class="cancel">&nbsp;</em>Cancel</span></a>
	    </div>
	</div>
</body>
</html>
